### PR TITLE
Fix problem with the functions that return null when they are operated with other parameters

### PR DESCRIPTION
**Pull request by marior21**
-Fix problem with the functions that return null when they are operated with other parameters, either in sum, divisions, etc. or in comparisons.
-For comparisons it is necessary to allow null parameters with AllowNullParameter
-Modify comparison method since when comparing a parameter with null value and an integer, it failed.
-Add tests to validate the changes made
-Fix test that failed because the message of the exception was in Spanish and in the test was compared with a message in English

### CODE REVIEW

**Comment by rhaikonen** [comment]
I'd like to have this, please.

**Comment by marior21** [comment]
@rhaikonen I'm waiting that @pitermarx to validate the changes

**Comment by pitermarx** [comment]
This makes sense to me. Even though it is a behaviour change, as it is behind a flag I'd be willing to merge it.
Could you make a brief description of the expected behaviour of each operation (Binary and Unary) with and without the AllowNull parameter?

**Comment by pitermarx** [comment]
closing due to inactivity

**Pull request closed without merging**
