### PR TITLE
Allow arithmetic between single/double and decimal values.

### PR DESCRIPTION
**Pull request by mikeycooper**
Adds support for +, -, *, /, % and unit tests for all permutations.

### CODE REVIEW

**Comment by pitermarx** [comment]
this comes up a lot.
the way I understand the original intent of the creator, is that NCalc should behave as .net.
in .net you cannot use a decimal and a floating point number in the same operation.
The error is the same as in NCalc
e.g. Operator Y cannot be applied to operands of type 'decimal' and 'double'

For this reason I dont think I will merge this PR.
The user should decide "a priori" if the calculations will be done with decimal or floating point numbers

**Comment by mikeycooper** [comment]
If that was the original intent, the author was not consistent with it. You can see in Numbers.cs;9b27146b, the conversion was already taking place for some operators (addition of Single or Double to a Decimal and vice versa). They even created a test (ShouldAddDoubleAndDecimal) to ensure that you could add the two together. I figured they just abandoned the project before finishing up with the rest of the operators.

So right now, you're in this weird state where you can only add together a single/double and a decimal.

**Comment by pitermarx** [comment]
you are correct. Let me think about it

**Comment by mikeycooper** [comment]
If you do decide to incorporate this change, would you be able to roll out a new nuget package? I'd love to use this within my project rather than copying the code over.

**Comment by pitermarx** [comment]
Yes. Should this be a minor or a patch?

## 

Pedro Marques

No dia 16/06/2016, às 23:48, Mikey Cooper notifications@github.com escreveu:

**Comment by mikeycooper** [comment]
No new APIs at all, so I'd say patch.

**Comment by pitermarx** [comment]
I've decided to include this PR in the source.
The current state is not consistent and a Convert.ToDecimal seems reasonable to me since it was already there for add operations.
Thanks for your contribution
Thanks for all the tests

**Pull request merged**
